theme = "onedark"

[editor]
mouse = true
line-number = "relative"
auto-format = false # set per language
idle-timeout = 600
true-color = true
bufferline = "multiple"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.file-picker]
hidden = false

[editor.auto-pairs]

[editor.search]
wrap-around = false

[editor.whitespace]

[editor.indent-guides]
render = true
character = "&#9550;"

# ADD KEYREMAPS
