services:
  syncthing:
    image: syncthing/syncthing
    container-name: syncthing
    hostname: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_DIR}/syncthing:/var/syncthing
    ports:
      - 8384:8384 # web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # UDP file transfers
      - 21027:21027/udp # Local discovery broadcasts
    restart: unless-stopped
