services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    hostname: pihole
    #network_mode: host # use host instead of ports if using as DHCP server
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${PIHOLE_PASSWORD}
    volumes:
      - ${PIHOLE_DATA}/pihole:/etc/pihole
      - ${PIHOLE_DATA}/dnsmasq.d:/etc/dnsmasq.d
    ports:
      - 53:53/tcp
      - 53:53/udp
      #- 67:67/udp # only required if using as DHCP server
      - 5353:80/tcp
    cap_add:
      #- NET_ADMIN # only required if using as DHCP server
    restart: unless-stopped
