services:
  traefik:
    image: docker.io/library/traefik:v3.3
    container_name: traefik
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - ${DOCKER_SOCK}:/run/docker.sock:ro
      - ${TRAEFIK_DATA}/config:/etc/traefik:ro
      - ${TRAEFIK_DATA}/certs:/var/traefik/certs:rw
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - frontend
    restart: unless-stopped
