local o = vim.opt

o.breakindent = true
o.confirm = true -- confirm to save changes before exiting modified buffer
o.completeopt = "menu,menuone,noselect"
o.cursorline = true -- highlight line with cursor
o.expandtab = true -- turn tabs to spaces
o.hlsearch = false
o.ignorecase = true
o.incsearch = true
o.linebreak = false -- line wrap at convient points
o.list = true -- show some hidden chars like \t
o.mouse = "a" -- enable mouse mode
o.number = true
o.relativenumber = true
o.scrolloff = 5
o.shiftwidth = 4
o.sidescrolloff = 10 -- min 
o.signcolumn = "yes" -- always show sign column to prevent text shifting
o.smartcase = true
o.smartindent = true
o.softtabstop = 4
o.tabstop = 4
o.termguicolors = true -- true color support
o.undofile = true
o.updatetime = 250
o.wrap = false
